import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "How this was built",
  description: "The seeded data model, D3 rendering approach, and code-splitting behind this dashboard.",
  alternates: { canonical: "/how-this-was-built" },
};

export default function HowThisWasBuiltPage() {
  return (
    <div className="mx-auto max-w-2xl px-5 py-14 sm:px-6 sm:py-20">
      <Link href="/" className="font-mono text-xs text-[var(--color-neutral-600)] hover:text-[var(--color-accent)]">
        ← Back to the dashboard
      </Link>

      <h1 className="mt-6 font-[family-name:var(--font-heading)] text-3xl font-bold tracking-tight text-[var(--color-neutral-800)] sm:text-4xl">
        How this was built
      </h1>

      <div className="prose-article mt-8">
        <p>
          Every number on this dashboard is fictional, but none of it is
          random. The data is generated by a seeded pseudo-random function, so
          the same filter combination always produces the same figures, on the
          server and in the browser.
        </p>

        <h2>Why seeded and not random</h2>
        <p>
          Next.js renders these components on the server and then hydrates them
          on the client. If the data came from <code>Math.random()</code>, the
          two passes would disagree and React would throw a hydration mismatch.
          A small <code>mulberry32</code> generator, seeded from a hash of the
          active filters, gives every render the same sequence:
        </p>
        <pre>{`const random = mulberry32(hashString(\`attendance:\${range}:\${band}\`));`}</pre>
        <p>
          It also means a link to a particular filter state shows the same
          chart to whoever opens it, which a demo with genuinely random numbers
          could never do.
        </p>

        <h2>D3 by hand, not through a wrapper</h2>
        <p>
          The grade distribution chart and the wellbeing heatmap are drawn with
          D3 directly against the DOM: <code>scaleBand</code>,{" "}
          <code>scaleLinear</code>, <code>scaleSequential</code>, manually
          drawn axes, and the <code>.join()</code> enter/update/exit pattern
          with transitions. No chart-library wrapper sits in between.
        </p>
        <p>
          The attendance chart is Chart.js instead, because a smoothed time
          series with a filled area is exactly what that library is good at.
          Using both, and picking per chart, is the honest version of
          &quot;knows D3 and Chart.js&quot;.
        </p>

        <h2>The at-risk signal</h2>
        <p>
          The three charts each show one dimension in aggregate, which means
          none of them can answer the question a head of year actually has:
          which students are struggling on more than one front at once.
        </p>
        <p>
          So there is a fourth dataset, a synthetic per-student roster where
          attendance, grades, and wellbeing exist on the same row. A student is
          flagged when all three fall below threshold. The KPI deltas come from
          the same source: attendance and wellbeing compare the two halves of
          the selected period, grades and the roster compare against a
          previous-period seed variant. Nothing on the KPI row is a number
          invented separately from the charts.
        </p>
        <p>
          The drill-down table uses anonymised ids. Inventing plausible student
          names for a public demo would make the fiction harder to see, not
          easier.
        </p>

        <h2>Keeping the charts out of the initial bundle</h2>
        <p>
          D3 and Chart.js are both large. Each visualisation is loaded through{" "}
          <code>next/dynamic</code> with <code>ssr: false</code>, so neither
          library is in the first payload and neither can become the page&apos;s
          largest contentful paint.
        </p>
        <p>
          That was verified rather than assumed: grepping the built{" "}
          <code>.next/static/chunks</code> output for library-specific strings,
          then checking those chunk filenames are absent from the script tags
          in the prerendered HTML.
        </p>
      </div>
    </div>
  );
}
