import type { ModuleInfo } from '@/types';

export const MODULES: ModuleInfo[] = [
  {
    id: 'javascript',
    title: 'JavaScript Core',
    description: 'The foundation — execution context, closures, this, prototypes, event loop, promises, and ES6+',
    icon: 'JS',
    color: 'yellow',
    topics: [
      { id: 'execution-context', title: 'Execution Context & Hoisting', estimatedTime: '45 min', moduleId: 'javascript' },
      { id: 'closures', title: 'Closures', estimatedTime: '40 min', moduleId: 'javascript' },
      { id: 'this-keyword', title: 'The `this` Keyword', estimatedTime: '35 min', moduleId: 'javascript' },
      { id: 'prototypes', title: 'Prototypes & Inheritance', estimatedTime: '40 min', moduleId: 'javascript' },
      { id: 'event-loop', title: 'Event Loop & Async JS', estimatedTime: '60 min', moduleId: 'javascript' },
      { id: 'promises', title: 'Promises & Async/Await', estimatedTime: '50 min', moduleId: 'javascript' },
      { id: 'es6-features', title: 'ES6+ Features Deep Dive', estimatedTime: '45 min', moduleId: 'javascript' },
      { id: 'array-object-methods', title: 'Array & Object Methods', estimatedTime: '40 min', moduleId: 'javascript' },
      { id: 'type-coercion', title: 'Type Coercion & Equality', estimatedTime: '30 min', moduleId: 'javascript' },
      { id: 'scope', title: 'Scope & Variable Declarations', estimatedTime: '35 min', moduleId: 'javascript' },
    ],
  },
  {
    id: 'react',
    title: 'React Deep Dive',
    description: 'Virtual DOM, Fiber, hooks, state management, performance, patterns, and React 18/19',
    icon: 'Re',
    color: 'cyan',
    topics: [
      { id: 'how-react-works', title: 'How React Works Under the Hood', estimatedTime: '50 min', moduleId: 'react' },
      { id: 'lifecycle', title: 'Component Lifecycle (Class vs Functional)', estimatedTime: '40 min', moduleId: 'react' },
      { id: 'hooks', title: 'Hooks — Complete Guide', estimatedTime: '90 min', moduleId: 'react' },
      { id: 'custom-hooks', title: 'Custom Hooks', estimatedTime: '60 min', moduleId: 'react' },
      { id: 'state-management', title: 'State Management Patterns', estimatedTime: '60 min', moduleId: 'react' },
      { id: 'performance', title: 'React Performance Optimization', estimatedTime: '55 min', moduleId: 'react' },
      { id: 'patterns', title: 'React Patterns', estimatedTime: '50 min', moduleId: 'react' },
      { id: 'error-handling', title: 'Error Handling in React', estimatedTime: '30 min', moduleId: 'react' },
      { id: 'forms', title: 'Forms in React', estimatedTime: '40 min', moduleId: 'react' },
      { id: 'react-18-19', title: 'React 18/19 Features', estimatedTime: '45 min', moduleId: 'react' },
    ],
  },
  {
    id: 'nextjs',
    title: 'Next.js Mastery',
    description: 'App Router, Server Components, data fetching, caching, middleware, and deployment',
    icon: 'N',
    color: 'white',
    topics: [
      { id: 'app-router', title: 'App Router Architecture', estimatedTime: '50 min', moduleId: 'nextjs' },
      { id: 'server-client-components', title: 'Server vs Client Components', estimatedTime: '55 min', moduleId: 'nextjs' },
      { id: 'data-fetching', title: 'Data Fetching Patterns', estimatedTime: '60 min', moduleId: 'nextjs' },
      { id: 'rendering', title: 'Rendering Strategies', estimatedTime: '50 min', moduleId: 'nextjs' },
      { id: 'caching', title: 'Caching in Next.js', estimatedTime: '65 min', moduleId: 'nextjs' },
      { id: 'middleware', title: 'Middleware', estimatedTime: '35 min', moduleId: 'nextjs' },
      { id: 'image-font', title: 'Image & Font Optimization', estimatedTime: '30 min', moduleId: 'nextjs' },
      { id: 'seo-metadata', title: 'SEO & Metadata', estimatedTime: '35 min', moduleId: 'nextjs' },
      { id: 'authentication', title: 'Authentication in Next.js', estimatedTime: '50 min', moduleId: 'nextjs' },
      { id: 'deployment', title: 'Deployment & Production', estimatedTime: '40 min', moduleId: 'nextjs' },
    ],
  },
  {
    id: 'typescript',
    title: 'TypeScript for React',
    description: 'Fundamentals, generics, utility types, React-specific patterns, and advanced TypeScript',
    icon: 'TS',
    color: 'blue',
    topics: [
      { id: 'fundamentals', title: 'TypeScript Fundamentals', estimatedTime: '50 min', moduleId: 'typescript' },
      { id: 'generics', title: 'Generics', estimatedTime: '45 min', moduleId: 'typescript' },
      { id: 'utility-types', title: 'Utility Types', estimatedTime: '40 min', moduleId: 'typescript' },
      { id: 'react-patterns', title: 'TypeScript with React Patterns', estimatedTime: '55 min', moduleId: 'typescript' },
      { id: 'advanced', title: 'Advanced TypeScript', estimatedTime: '60 min', moduleId: 'typescript' },
    ],
  },
  {
    id: 'system-design',
    title: 'Frontend System Design',
    description: 'Framework for approaching design questions, with 5 full walkthroughs',
    icon: 'SD',
    color: 'purple',
    topics: [
      { id: 'approach', title: 'How to Approach System Design', estimatedTime: '30 min', moduleId: 'system-design' },
      { id: 'analytics-dashboard', title: 'Design: Analytics Dashboard', estimatedTime: '60 min', moduleId: 'system-design' },
      { id: 'ecommerce', title: 'Design: E-Commerce Product Page', estimatedTime: '50 min', moduleId: 'system-design' },
      { id: 'chat-app', title: 'Design: Chat Application', estimatedTime: '55 min', moduleId: 'system-design' },
      { id: 'infinite-scroll', title: 'Design: Infinite Scroll Feed', estimatedTime: '45 min', moduleId: 'system-design' },
      { id: 'form-builder', title: 'Design: Form Builder', estimatedTime: '50 min', moduleId: 'system-design' },
    ],
  },
  {
    id: 'performance',
    title: 'Performance & Web Vitals',
    description: 'Core Web Vitals, bundle optimization, network performance, and runtime performance',
    icon: 'Pf',
    color: 'green',
    topics: [
      { id: 'core-web-vitals', title: 'Core Web Vitals', estimatedTime: '50 min', moduleId: 'performance' },
      { id: 'bundle-optimization', title: 'Bundle Optimization', estimatedTime: '40 min', moduleId: 'performance' },
      { id: 'network-performance', title: 'Network Performance', estimatedTime: '35 min', moduleId: 'performance' },
      { id: 'runtime-performance', title: 'Runtime Performance', estimatedTime: '45 min', moduleId: 'performance' },
    ],
  },
  {
    id: 'testing',
    title: 'Testing',
    description: 'Testing philosophy, Jest, React Testing Library, and E2E testing',
    icon: 'T',
    color: 'red',
    topics: [
      { id: 'philosophy', title: 'Testing Philosophy', estimatedTime: '25 min', moduleId: 'testing' },
      { id: 'jest', title: 'Jest Fundamentals', estimatedTime: '45 min', moduleId: 'testing' },
      { id: 'rtl', title: 'React Testing Library', estimatedTime: '55 min', moduleId: 'testing' },
      { id: 'e2e', title: 'E2E Testing Basics', estimatedTime: '35 min', moduleId: 'testing' },
    ],
  },
  {
    id: 'behavioral',
    title: 'Behavioral Interview Prep',
    description: 'STAR method, prepared stories using your CV, and questions to ask interviewers',
    icon: 'B',
    color: 'orange',
    topics: [
      { id: 'star-method', title: 'STAR Method', estimatedTime: '20 min', moduleId: 'behavioral' },
      { id: 'prepared-stories', title: 'Prepared Stories (Your CV)', estimatedTime: '60 min', moduleId: 'behavioral' },
      { id: 'questions-to-ask', title: 'Questions to Ask the Interviewer', estimatedTime: '20 min', moduleId: 'behavioral' },
    ],
  },
  {
    id: 'coding-challenges',
    title: 'Coding Challenges',
    description: 'DOM manipulation, React coding challenges, and LeetCode essentials',
    icon: 'CC',
    color: 'pink',
    topics: [
      { id: 'dom-manipulation', title: 'DOM Manipulation Challenges', estimatedTime: '90 min', moduleId: 'coding-challenges' },
      { id: 'react-challenges', title: 'React Coding Challenges', estimatedTime: '120 min', moduleId: 'coding-challenges' },
      { id: 'leetcode', title: 'LeetCode Essentials', estimatedTime: '90 min', moduleId: 'coding-challenges' },
    ],
  },
  {
    id: 'graphql',
    title: 'GraphQL',
    description: 'Queries, mutations, subscriptions, Apollo Client, and GraphQL vs REST',
    icon: 'GQL',
    color: 'pink',
    topics: [
      { id: 'fundamentals', title: 'GraphQL Fundamentals', estimatedTime: '40 min', moduleId: 'graphql' },
      { id: 'queries-mutations', title: 'Queries & Mutations', estimatedTime: '35 min', moduleId: 'graphql' },
      { id: 'subscriptions', title: 'Subscriptions & Real-time', estimatedTime: '30 min', moduleId: 'graphql' },
      { id: 'apollo-client', title: 'Apollo Client with React', estimatedTime: '45 min', moduleId: 'graphql' },
    ],
  },
  {
    id: 'git',
    title: 'Git & GitHub',
    description: 'Branching, merging, rebasing, stashing, pull requests, and real-world team workflows',
    icon: 'Git',
    color: 'orange',
    topics: [
      { id: 'core-concepts', title: 'Core Concepts & Staging', estimatedTime: '30 min', moduleId: 'git' },
      { id: 'branching-merging', title: 'Branching & Merging', estimatedTime: '40 min', moduleId: 'git' },
      { id: 'rebase-cherry-pick', title: 'Rebase & Cherry-pick', estimatedTime: '35 min', moduleId: 'git' },
      { id: 'stash-reset-revert', title: 'Stash, Reset & Revert', estimatedTime: '30 min', moduleId: 'git' },
      { id: 'remotes-github', title: 'Remotes, Pull Requests & GitHub', estimatedTime: '40 min', moduleId: 'git' },
      { id: 'workflows', title: 'Team Workflows & Best Practices', estimatedTime: '30 min', moduleId: 'git' },
    ],
  },
  {
    id: 'rapid-fire',
    title: 'الأسئلة الأكثر تكرارًا',
    description: 'مراجعة سريعة قبل الانترفيو: أشهر أسئلة JavaScript و React و Next.js بإجابات مختصرة',
    icon: 'Q',
    color: 'amber',
    topics: [
      { id: 'js-essentials', title: 'أساسيات JavaScript المتكررة', estimatedTime: '50 min', moduleId: 'rapid-fire' },
      { id: 'react-essentials', title: 'أساسيات React المتكررة', estimatedTime: '55 min', moduleId: 'rapid-fire' },
    ],
  },
];

export const MODULE_MAP = Object.fromEntries(MODULES.map((m) => [m.id, m]));
